// <auto-generated />
namespace ERS_Demo_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedphonetostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedphonetostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201905211406501_changed phone to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
